data:
  data_dir: "dataset"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  img_size: 224
  batch_size: 32
  num_workers: 4

model:
  architecture: "resnet18"
  num_classes: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 10
  pretrained: true
  weights: "IMAGENET1K_V1"

training:
  device: "cpu"
  checkpoint_dir: "checkpoints"
  early_stopping_patience: 5

logging:
  log_dir: "logs"

monitoring:
  mlflow_tracking_uri: "mlruns"
  experiment_name: "font_classification"
  log_interval: 10

api:
  host: "0.0.0.0"
  port: 8000
  model_path: "checkpoints/best_model.pth"
